"""empty message

Revision ID: 04ed2a75dd93
Revises: 27ba179b7e7b
Create Date: 2019-05-24 15:35:17.567340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ed2a75dd93'
down_revision = '27ba179b7e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_location',
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location'], ['location.id'], ),
    sa.ForeignKeyConstraint(['service'], ['service.name'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_location')
    # ### end Alembic commands ###
