"""empty message

Revision ID: 27ba179b7e7b
Revises: dddd8973ad7f
Create Date: 2019-05-24 15:26:07.386568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27ba179b7e7b'
down_revision = 'dddd8973ad7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('location', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service', 'location', ['location'], ['id'])
    op.drop_column('service', 'lng')
    op.drop_column('service', 'lat')
    op.drop_column('service', 'specific_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('specific_location', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('service', sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('service', sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column('service', 'location')
    # ### end Alembic commands ###
