"""another migration

Revision ID: 300f0bb75e41
Revises: 948f5a9ffbf5
Create Date: 2019-05-14 18:40:46.006818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300f0bb75e41'
down_revision = '948f5a9ffbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('passed_by_on_route', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'location', 'route', ['passed_by_on_route'], ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'passed_by_on_route')
    # ### end Alembic commands ###
