"""changing some table name

Revision ID: 4937d7e92862
Revises: 1cd716abe758
Create Date: 2019-05-07 14:04:53.287661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4937d7e92862'
down_revision = '1cd716abe758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveler',
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('middle_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('salt', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('traveller')
    op.add_column('driver', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('driver', sa.Column('email', sa.Text(), nullable=False))
    op.add_column('driver', sa.Column('first_name', sa.Text(), nullable=False))
    op.add_column('driver', sa.Column('last_name', sa.Text(), nullable=False))
    op.add_column('driver', sa.Column('middle_name', sa.Text(), nullable=True))
    op.add_column('driver', sa.Column('password', sa.Text(), nullable=False))
    op.add_column('driver', sa.Column('salt', sa.Text(), nullable=False))
    op.add_column('driver', sa.Column('user_name', sa.Text(), nullable=False))
    op.drop_column('driver', 'age')
    op.drop_column('driver', 'name')
    op.add_column('exec', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('exec', sa.Column('email', sa.Text(), nullable=False))
    op.add_column('exec', sa.Column('first_name', sa.Text(), nullable=False))
    op.add_column('exec', sa.Column('last_name', sa.Text(), nullable=False))
    op.add_column('exec', sa.Column('middle_name', sa.Text(), nullable=True))
    op.add_column('exec', sa.Column('password', sa.Text(), nullable=False))
    op.add_column('exec', sa.Column('salt', sa.Text(), nullable=False))
    op.add_column('exec', sa.Column('user_name', sa.Text(), nullable=False))
    op.drop_column('exec', 'age')
    op.drop_column('exec', 'name')
    op.add_column('ticket', sa.Column('traveler', sa.Text(), nullable=False))
    op.drop_constraint('ticket_traveller_fkey', 'ticket', type_='foreignkey')
    op.create_foreign_key(None, 'ticket', 'traveler', ['traveler'], ['id'])
    op.drop_column('ticket', 'traveller')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('traveller', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.create_foreign_key('ticket_traveller_fkey', 'ticket', 'traveller', ['traveller'], ['id'])
    op.drop_column('ticket', 'traveler')
    op.add_column('exec', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('exec', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('exec', 'user_name')
    op.drop_column('exec', 'salt')
    op.drop_column('exec', 'password')
    op.drop_column('exec', 'middle_name')
    op.drop_column('exec', 'last_name')
    op.drop_column('exec', 'first_name')
    op.drop_column('exec', 'email')
    op.drop_column('exec', 'birthday')
    op.add_column('driver', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('driver', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('driver', 'user_name')
    op.drop_column('driver', 'salt')
    op.drop_column('driver', 'password')
    op.drop_column('driver', 'middle_name')
    op.drop_column('driver', 'last_name')
    op.drop_column('driver', 'first_name')
    op.drop_column('driver', 'email')
    op.drop_column('driver', 'birthday')
    op.create_table('traveller',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='traveller_pkey')
    )
    op.drop_table('traveler')
    # ### end Alembic commands ###
