"""added constraints to database columns for better integrity

Revision ID: 4b08e59fc9e7
Revises: 
Create Date: 2019-05-06 10:02:58.975360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b08e59fc9e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('age', sa.Integer(), nullable=True))
    op.alter_column('driver', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('exec', sa.Column('age', sa.Integer(), nullable=True))
    op.alter_column('exec', 'matatu_service',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('exec', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('location', 'lat',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('location', 'lng',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('location', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('matatu', 'matatu_service',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('route', 'from_location',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('route', 'to_location',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ticket', 'cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ticket', 'driver',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ticket', 'matatu',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ticket', 'pick_up_lat',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ticket', 'pick_up_lng',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ticket', 'pick_up_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ticket', 'route',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ticket', 'traveller',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('traveller', sa.Column('age', sa.Integer(), nullable=True))
    op.alter_column('traveller', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traveller', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('traveller', 'age')
    op.alter_column('ticket', 'traveller',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ticket', 'route',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ticket', 'pick_up_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ticket', 'pick_up_lng',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ticket', 'pick_up_lat',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ticket', 'matatu',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ticket', 'driver',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ticket', 'cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('route', 'to_location',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('route', 'from_location',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matatu', 'matatu_service',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('location', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('location', 'lng',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('location', 'lat',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('exec', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('exec', 'matatu_service',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('exec', 'age')
    op.alter_column('driver', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('driver', 'age')
    # ### end Alembic commands ###
