"""empty message

Revision ID: 4d20d1cc007e
Revises: cba5b40eb536
Create Date: 2019-05-31 10:59:08.670867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d20d1cc007e'
down_revision = 'cba5b40eb536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'user_name')
    op.drop_column('exec', 'user_name')
    op.drop_column('traveler', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traveler', sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('exec', sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('driver', sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
