"""empty message

Revision ID: 54a44df9c1d3
Revises: 4d20d1cc007e
Create Date: 2019-06-04 12:50:48.919145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a44df9c1d3'
down_revision = '4d20d1cc007e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('from_town_id', sa.Integer(), nullable=False))
    op.add_column('route', sa.Column('to_town_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'route', 'location', ['from_town_id'], ['id'])
    op.create_foreign_key(None, 'route', 'location', ['to_town_id'], ['id'])
    op.drop_column('route', 'to_town')
    op.drop_column('route', 'from_town')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('from_town', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('route', sa.Column('to_town', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_column('route', 'to_town_id')
    op.drop_column('route', 'from_town_id')
    # ### end Alembic commands ###
