"""empty message

Revision ID: 5aa3707c4677
Revises: b0b75d53babf
Create Date: 2019-05-27 09:56:51.380753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa3707c4677'
down_revision = 'b0b75d53babf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matatu_routes',
    sa.Column('matatu_registration', sa.Text(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matatu_registration'], ['matatu.registration'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.number'], )
    )
    op.drop_constraint('route_price_service_matatu_registration_fkey', 'route_price_service', type_='foreignkey')
    op.drop_column('route_price_service', 'matatu_registration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_price_service', sa.Column('matatu_registration', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key('route_price_service_matatu_registration_fkey', 'route_price_service', 'matatu', ['matatu_registration'], ['registration'])
    op.drop_table('matatu_routes')
    # ### end Alembic commands ###
