"""empty message

Revision ID: 6234719ce67c
Revises: 843fb230d655
Create Date: 2019-06-09 09:05:13.050445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6234719ce67c'
down_revision = '843fb230d655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'matatu_queue', ['matatu_registration'])
    op.drop_constraint('service_location_fkey', 'service', type_='foreignkey')
    op.drop_column('service', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('service_location_fkey', 'service', 'location', ['location'], ['id'])
    op.drop_constraint(None, 'matatu_queue', type_='unique')
    # ### end Alembic commands ###
