"""empty message

Revision ID: 843fb230d655
Revises: 54a44df9c1d3
Create Date: 2019-06-04 13:07:51.276695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843fb230d655'
down_revision = '54a44df9c1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route', 'from_town_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('route', 'to_town_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('route', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('route', 'to_town_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('route', 'from_town_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
