"""empty message

Revision ID: 8d6472a2d247
Revises: 6234719ce67c
Create Date: 2019-06-09 09:19:45.677072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6472a2d247'
down_revision = '6234719ce67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('phone_number', sa.Text(), nullable=True))
    op.add_column('exec', sa.Column('phone_number', sa.Text(), nullable=True))
    op.add_column('traveler', sa.Column('phone_number', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traveler', 'phone_number')
    op.drop_column('exec', 'phone_number')
    op.drop_column('driver', 'phone_number')
    # ### end Alembic commands ###
