"""empty message

Revision ID: 915efad0c32f
Revises: d474b4497ef5
Create Date: 2019-05-27 10:59:42.389087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915efad0c32f'
down_revision = 'd474b4497ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taken_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matatu_queue_instance_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matatu_queue_instance_id'], ['matatu_queue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matatu_queue_instance_id', 'seat_number', name='unique_component_commit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taken_seats')
    # ### end Alembic commands ###
