"""empty message

Revision ID: 9161b3c55564
Revises: fda51c2d97c9
Create Date: 2019-05-28 12:54:20.081158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9161b3c55564'
down_revision = 'fda51c2d97c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exec', 'matatu_service',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exec', 'matatu_service',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
