"""empty message

Revision ID: 997e4c8a1774
Revises: cc9e5fdf08d0
Create Date: 2019-05-24 12:43:03.769880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997e4c8a1774'
down_revision = 'cc9e5fdf08d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'location', ['lng', 'lat'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='unique')
    # ### end Alembic commands ###
