"""empty message

Revision ID: a570181e3b89
Revises: 04ed2a75dd93
Create Date: 2019-05-25 08:58:19.785605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a570181e3b89'
down_revision = '04ed2a75dd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_price_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('route', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['route'], ['route.number'], ),
    sa.ForeignKeyConstraint(['service'], ['service.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('service_route')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_route',
    sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('route', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['route'], ['route.number'], name='service_route_route_fkey'),
    sa.ForeignKeyConstraint(['service'], ['service.name'], name='service_route_service_fkey')
    )
    op.drop_table('route_price_service')
    # ### end Alembic commands ###
