"""empty message

Revision ID: b00bd8ded52c
Revises: 
Create Date: 2019-06-12 12:53:26.617285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00bd8ded52c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('fulfilled', sa.Boolean(), nullable=False))
    op.add_column('ticket', sa.Column('payed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'payed')
    op.drop_column('ticket', 'fulfilled')
    # ### end Alembic commands ###
