"""empty message

Revision ID: cba5b40eb536
Revises: 9161b3c55564
Create Date: 2019-05-30 20:05:36.543127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba5b40eb536'
down_revision = '9161b3c55564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'matatu_service')
    op.drop_column('exec', 'matatu_service')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exec', sa.Column('matatu_service', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('driver', sa.Column('matatu_service', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
