"""empty message

Revision ID: cc9e5fdf08d0
Revises: f7feb32e67d4
Create Date: 2019-05-24 12:40:49.890911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9e5fdf08d0'
down_revision = 'f7feb32e67d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('from_town', sa.Text(), nullable=False))
    op.add_column('route', sa.Column('to_town', sa.Text(), nullable=False))
    op.drop_constraint('route_from_location_fkey', 'route', type_='foreignkey')
    op.drop_constraint('route_to_location_fkey', 'route', type_='foreignkey')
    op.drop_column('route', 'to_location')
    op.drop_column('route', 'from_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('from_location', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('route', sa.Column('to_location', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('route_to_location_fkey', 'route', 'location', ['to_location'], ['id'])
    op.create_foreign_key('route_from_location_fkey', 'route', 'location', ['from_location'], ['id'])
    op.drop_column('route', 'to_town')
    op.drop_column('route', 'from_town')
    # ### end Alembic commands ###
