"""empty message

Revision ID: d474b4497ef5
Revises: 5aa3707c4677
Create Date: 2019-05-27 10:06:32.832064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd474b4497ef5'
down_revision = '5aa3707c4677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matatu_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_of_vacant_seats', sa.Integer(), nullable=False),
    sa.Column('route_price_service_id', sa.Integer(), nullable=False),
    sa.Column('matatu_registration', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['matatu_registration'], ['matatu.registration'], ),
    sa.ForeignKeyConstraint(['route_price_service_id'], ['route_price_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matatu_queue')
    # ### end Alembic commands ###
