"""empty message

Revision ID: dddd8973ad7f
Revises: 997e4c8a1774
Create Date: 2019-05-24 15:23:02.570546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddd8973ad7f'
down_revision = '997e4c8a1774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('service', sa.Column('lng', sa.Float(), nullable=False))
    op.add_column('service', sa.Column('specific_location', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'specific_location')
    op.drop_column('service', 'lng')
    op.drop_column('service', 'lat')
    # ### end Alembic commands ###
