"""empty message

Revision ID: ef92af8720c9
Revises: 6a5ceee87da7
Create Date: 2019-05-25 09:49:06.169014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef92af8720c9'
down_revision = '6a5ceee87da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_price_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('route', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['route'], ['route.number'], ),
    sa.ForeignKeyConstraint(['service'], ['service.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('service_route')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_route',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('route', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['route'], ['route.number'], name='service_route_route_fkey'),
    sa.ForeignKeyConstraint(['service'], ['service.name'], name='service_route_service_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_route_pkey')
    )
    op.drop_table('route_price_service')
    # ### end Alembic commands ###
