"""empty message

Revision ID: f7feb32e67d4
Revises: 300f0bb75e41
Create Date: 2019-05-24 12:02:16.664319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7feb32e67d4'
down_revision = '300f0bb75e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('extension', sa.Text(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('driver', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['driver'], ['driver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_on_route',
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('route', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location'], ['location.id'], ),
    sa.ForeignKeyConstraint(['route'], ['route.number'], )
    )
    op.add_column('location', sa.Column('specific_location', sa.Text(), nullable=False))
    op.add_column('location', sa.Column('town', sa.Text(), nullable=False))
    op.drop_constraint('location_passed_by_on_route_fkey', 'location', type_='foreignkey')
    op.drop_column('location', 'name')
    op.drop_column('location', 'passed_by_on_route')
    op.add_column('log', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.drop_column('log', 'time')
    op.add_column('route', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'id')
    op.add_column('log', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('log', 'datetime')
    op.add_column('location', sa.Column('passed_by_on_route', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key('location_passed_by_on_route_fkey', 'location', 'route', ['passed_by_on_route'], ['number'])
    op.drop_column('location', 'town')
    op.drop_column('location', 'specific_location')
    op.drop_table('location_on_route')
    op.drop_table('driver_picture')
    # ### end Alembic commands ###
