"""empty message

Revision ID: f942872b660b
Revises: 690725dcf256
Create Date: 2019-05-27 16:55:01.219759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f942872b660b'
down_revision = '690725dcf256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matatu', sa.Column('driver_id', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'matatu', 'driver', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matatu', type_='foreignkey')
    op.drop_column('matatu', 'driver_id')
    # ### end Alembic commands ###
