"""empty message

Revision ID: fced6dea1d7b
Revises: 8d6472a2d247
Create Date: 2019-06-09 09:21:55.065925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fced6dea1d7b'
down_revision = '8d6472a2d247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'phone_number')
    op.drop_column('exec', 'phone_number')
    op.drop_column('traveler', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traveler', sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exec', sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('driver', sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
