"""empty message

Revision ID: fda51c2d97c9
Revises: f942872b660b
Create Date: 2019-05-27 17:02:12.438346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda51c2d97c9'
down_revision = 'f942872b660b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'driver',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'driver',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
