"""empty message

Revision ID: fe6d24781ad8
Revises: ef92af8720c9
Create Date: 2019-05-25 09:50:46.048235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6d24781ad8'
down_revision = 'ef92af8720c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_price_service', sa.Column('route_number', sa.Integer(), nullable=True))
    op.add_column('route_price_service', sa.Column('service_name', sa.Text(), nullable=True))
    op.drop_constraint('route_price_service_service_fkey', 'route_price_service', type_='foreignkey')
    op.drop_constraint('route_price_service_route_fkey', 'route_price_service', type_='foreignkey')
    op.create_foreign_key(None, 'route_price_service', 'service', ['service_name'], ['name'])
    op.create_foreign_key(None, 'route_price_service', 'route', ['route_number'], ['number'])
    op.drop_column('route_price_service', 'route')
    op.drop_column('route_price_service', 'service')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_price_service', sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('route_price_service', sa.Column('route', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'route_price_service', type_='foreignkey')
    op.drop_constraint(None, 'route_price_service', type_='foreignkey')
    op.create_foreign_key('route_price_service_route_fkey', 'route_price_service', 'route', ['route'], ['number'])
    op.create_foreign_key('route_price_service_service_fkey', 'route_price_service', 'service', ['service'], ['name'])
    op.drop_column('route_price_service', 'service_name')
    op.drop_column('route_price_service', 'route_number')
    # ### end Alembic commands ###
